version: 2

builds:
  - binary: vulners
    main: ./cmd/vulners/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/kidoz/vulners-cli/internal/cmd.Version={{.Version}}'
      - -X 'github.com/kidoz/vulners-cli/internal/cmd.Commit={{.Commit}}'
      - -X 'github.com/kidoz/vulners-cli/internal/cmd.Date={{.Date}}'

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
